thisdir = class/System.Management
SUBDIRS = 
include ../../build/rules.make

DEP_LIBS = System System.Configuration.Install

LIBRARY = System.Management.dll
LIB_MCS_FLAGS = /r:$(corlib) /r:System.dll /r:System.Configuration.Install.dll
NO_TEST = yes

include ../../build/library.make
