thisdir = class/Microsoft.CSharp
SUBDIRS = 
include ../../build/rules.make

DEP_LIBS = System.Core Mono.CSharp

LIBRARY = Microsoft.CSharp.dll

LIB_MCS_FLAGS = -r:System.Core.dll -r:Mono.CSharp.dll

include ../../build/library.make

