thisdir = class/Mono.Reflection.Emit.Save
SUBDIRS =
include ../../build/rules.make

LIBRARY = Mono.Reflection.Emit.Save.dll
LIB_REFS = System Mono.Cecil
LIB_MCS_FLAGS =

NO_TEST = yes

include ../../build/library.make
