thisdir = class/SystemWebTestShim
include ../../build/rules.make

DEP_LIBS = System.Web

LIBRARY = SystemWebTestShim.dll

LIB_MCS_FLAGS = -r:System.Web.dll

NO_INSTALL = yes
NO_SIGN_ASSEMBLY = yes

include $(topdir)/build/library.make
