thisdir = class/System.Configuration.Install
include ../../build/rules.make

DEP_LIBS = System System.XML

LIBRARY = System.Configuration.Install.dll
LIB_MCS_FLAGS = /r:$(corlib) /r:System.dll /r:System.Xml.dll

NO_TEST = yes

include ../../build/library.make
