thisdir = class/System.Dynamic
SUBDIRS = 
include ../../build/rules.make

DEP_LIBS = System System.Core

LIBRARY = System.Dynamic.dll

LIB_MCS_FLAGS = -unsafe -d:CODEPLEX_40 -r:System.Core.dll -r:System.dll

include ../../build/library.make

