thisdir = class/CustomMarshalers
SUBDIRS = 
include ../../build/rules.make

DEP_LIBS = System

LIBRARY = CustomMarshalers.dll
LIB_MCS_FLAGS = /r:$(corlib) /r:System.dll
NO_TEST = yes

include ../../build/library.make
